<?php
    include('components/l-headerHome/index.php');
    include('components/s-overview/index.php');
    include('components/s-stickyContent/integrations.php');
    include('components/s-stickyContent/siteDevelopment.php');
    include('components/s-portfolio/index.php');
    include('components/s-plansPricingHome/index.php');
    include('components/s-testmonials/index.php');
    include('components/s-blogPostsHome/index.php');
    include('components/s-faq/index.php');
    include('components/l-footer/index.php');
?>